# Generated by Django 3.1.4 on 2021-04-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=50)),
                ('locality', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=43)),
                ('pin', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('karachi', 'karachi'), ('Hyderabad\t', 'Hyderabad'), ('Karachi South', 'Karachi South'), ('Malir', 'Malir'), ('Korangi', 'Korangi\t')], max_length=24)),
                ('mobile', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('job_city', models.CharField(max_length=60)),
                ('profile_image', models.ImageField(blank=True, upload_to='profile_img')),
                ('my_file', models.FileField(blank=True, upload_to='doc')),
            ],
        ),
    ]
